export const TEMPLATES = [
  {
    id: 1,
    name: 'Classic',
    subtitle: 'Timeless & ATS-Safe',
    tags: ['Traditional', 'ATS-Friendly'],
    accent: '#1f2937',
    bg: '#f9fafb',
    preview: { headerAlign: 'center', sectionStyle: 'underline-dark', nameSize: 'xl' },
  },
  {
    id: 2,
    name: 'Academic',
    subtitle: 'LaTeX-Inspired',
    tags: ['Academic', 'Research'],
    accent: '#374151',
    bg: '#f9fafb',
    preview: { headerAlign: 'center', sectionStyle: 'smallcaps', nameSize: 'lg' },
  },
  {
    id: 3,
    name: 'Technical',
    subtitle: 'Developer-Focused',
    tags: ['Engineering', 'Tech'],
    accent: '#111827',
    bg: '#f9fafb',
    preview: { headerAlign: 'split', sectionStyle: 'left-border-dark', nameSize: 'xl' },
  },
  {
    id: 4,
    name: 'Modern',
    subtitle: 'Clean & Colorful',
    tags: ['Modern', 'Creative'],
    accent: '#0d9488',
    bg: '#f0fdfa',
    preview: { headerAlign: 'left', sectionStyle: 'underline-teal', nameSize: 'xl' },
  },
  {
    id: 5,
    name: 'Clean CS',
    subtitle: 'Minimal & Sharp',
    tags: ['CS', 'Minimal'],
    accent: '#1f2937',
    bg: '#f9fafb',
    preview: { headerAlign: 'center', sectionStyle: 'thin-rule', nameSize: 'lg' },
  },
  {
    id: 6,
    name: 'Corporate',
    subtitle: 'Professional Blue',
    tags: ['Corporate', 'Finance'],
    accent: '#1d4ed8',
    bg: '#eff6ff',
    preview: { headerAlign: 'center', sectionStyle: 'blue-accent', nameSize: 'lg' },
  },
  {
    id: 7,
    name: 'Minimal Blue',
    subtitle: 'Airy & Clean',
    tags: ['Minimal', 'Modern'],
    accent: '#2563eb',
    bg: '#f8faff',
    preview: { headerAlign: 'left', sectionStyle: 'blue-thin', nameSize: 'xl' },
  },
  {
    id: 8,
    name: 'Formal',
    subtitle: 'Traditional & Elegant',
    tags: ['Formal', 'Academic'],
    accent: '#374151',
    bg: '#fafafa',
    preview: { headerAlign: 'center', sectionStyle: 'formal-serif', nameSize: 'lg' },
  },
  {
    id: 9,
    name: 'Student',
    subtitle: 'Education-First',
    tags: ['Student', 'Fresher'],
    accent: '#059669',
    bg: '#f0fdf4',
    preview: { headerAlign: 'center', sectionStyle: 'green-accent', nameSize: 'lg' },
  },
  {
    id: 10,
    name: 'Jake Ryan',
    subtitle: 'Most Popular CS',
    tags: ['CS', 'Top Pick'],
    accent: '#111827',
    bg: '#f9fafb',
    preview: { headerAlign: 'center', sectionStyle: 'jake', nameSize: 'xl' },
  },
];
